version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: ewm-stat-server
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICES_STATSERVICE_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.Httpclient.log=errors,request

  ewm-db:
    image: postgres:15.1-alpine
    container_name: postgres-ewm-main-db
    ports:
      - "6540:5432"
    environment:
        - POSTGRES_DB=ewm-db
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
